## Quagmire.function

Like Underworld, quagmire provides a function interface that can be used to compose data and operations on the fly in order to construct model equations independent of whatever approach is used for solution. 

Noteably, these are _lazy_ function that are only evaluated when needed. More importantly, when evaluated, they also use the current state of any variables in their definition and so can be placed within timestepping loops where they will always use the information of the current timestep.

There are three kinds of lazy functions available in quagmire:

  - `MeshVariable` data containers that hold information on the mesh and can return that information at any point by interpolation (or, less reliably by extrapolation) and can also provide the gradient of the data using a cubic spline interpolant (see the documentation for `stripy` for details).
  
  - `parameter` is a floating point value that can be used for coefficients in an equation. The value of the parameter can be updated.
  
  - `virtual` variables which are operations on `MeshVariables` and `parameters` and contain no data record. 
  
  
These lazy functions are members of the `LazyEvaluation` class that defines the following methods / data

  - `evaluate(mesh | X, Y)` computes a snapshot of the value(s) at the mesh points of `mesh` or at the points given by X and Y
  
  - `fn_gradient(dir)` is a lazy function that can be evaluated to obtain the gradient in the direction `dir=(0|1)`
  
  - `description` is a string describing the result returned by `evaluate`. This is helpful because the function may be a cascade of operations. It very much helps to provide short, useful names for your mesh variables to get back reasonable descriptions. 
  
Note: at present no error checking is done for consistency between the mesh provided to evaluate and the one used to store the original data. This is very bad on our part !

In [1]:
from quagmire.tools import meshtools
from quagmire import FlatMesh
from quagmire.mesh import MeshVariable
from quagmire import function as fn
import numpy as np

### Working mesh

First we create a basic mesh so that we can define mesh variables and obbtain gradients etc.

In [2]:
minX, maxX = -5.0, 5.0
minY, maxY = -5.0, 5.0,
dx, dy = 0.02, 0.02

x, y, simplices = meshtools.elliptical_mesh(minX, maxX, minY, maxY, dx, dy)
DM = meshtools.create_DMPlex_from_points(x, y, bmask=None)
mesh = FlatMesh(DM, downhill_neighbours=1)

0 - Delaunay triangulation 0.6810939999999999s
0 - Calculate node weights and area 0.007634999999999614s
0 - Find boundaries 0.00029799999999990945s
0 - cKDTree 0.01638800000000007s
0 - Construct neighbour cloud array 0.6428510000000003s
0 - Construct rbf weights 0.0578890000000003s


### Basic usage

The functions can be demonstrated on the most basic example the `parameter` which is constant everywhere in the mesh. In fact, these operations work without any reference to the mesh since they are the same at all locations and their gradient is zero everywhere. 

In [3]:
A = fn.parameter(10.0)
B = fn.parameter(100.0)
print("Exp({}) = {}".format(A.value, fn.math.exp(A).evaluate(0.0,0.0)))
print("Exp({}) = {}".format(B.value, fn.math.exp(B).evaluate(0.0,0.0)))

## A is a proper lazy variable too so this is required to work

print("Exp({}) = {}".format(A.evaluate(0.0,0.0), fn.math.exp(A).evaluate(0.0,0.0)))

## And this is how to update A

A.value = 100.0
print("Exp({}) = {}".format(A.evaluate(0.0,0.0), fn.math.exp(A).evaluate(0.0,0.0)))

## This works too ... and note the floating point conversion
A(101)
print("Exp({}) = {}".format(A.evaluate(0.0,0.0), fn.math.exp(A).evaluate(0.0,0.0)))

## More complicated examples
print((fn.math.sin(A)**2.0 + fn.math.cos(A)**2.0).evaluate(0.0,0.0))

Exp(10.0) = 22026.465794806718
Exp(100.0) = 2.6881171418161356e+43
Exp(10.0) = 22026.465794806718
Exp(100.0) = 2.6881171418161356e+43
Exp(101.0) = 7.307059979368067e+43
1.0


### Descriptions

The lazy function carries a description string that tells you approximately what will happen when the function is evaluated. For example

In [4]:
print(A.description)
print((fn.math.sin(A)+fn.math.cos(B)).description)
print((fn.math.sin(A)**2.0 + fn.math.cos(A)**2.0).description)

## the description is printed by default if you call print on the function 

print((fn.math.sin(A)**2.0 + fn.math.cos(A)**2.0))



101.0
(SIN(101.0))+(COS(100.0))
((SIN(101.0))**(2.0))+((COS(101.0))**(2.0))
quagmire.fn: ((SIN(101.0))**(2.0))+((COS(101.0))**(2.0))


### Mesh Variables as functions

Mesh variables (`MeshVariables`) are also members of the `LazyEvaluation` class. They can be evaluated exactly as the paramters can, but it is also possible to obtain derivatives. Of course, they also have other properties beyond those of simple functions (see the MeshVariables examples in the XXXXX notebook for details).

Let us first define a mesh variable ... 

In [5]:
height = mesh.add_variable(name="h(X,Y)")
height.data = np.ones(mesh.npoints)
print(height)

[1. 1. 1. ... 1. 1. 1.]


We might introduce a universal scaling for the height variable. This could be useful if, say, the offset is something that we might want to change programmatically within a timestepping loop. 

In [6]:
h_scale = fn.parameter(2.0)
h_offset = fn.parameter(1.0)

scaled_height = height * h_scale + h_offset
print(scaled_height.description)
print(height.evaluate(mesh))
print(scaled_height.evaluate(mesh))

h_offset.value = 10.0
print(scaled_height.evaluate(mesh))

((h(X,Y))*(2.0))+(1.0)
[1. 1. 1. ... 1. 1. 1.]
[3. 3. 3. ... 3. 3. 3.]
[12. 12. 12. ... 12. 12. 12.]


We might wish to define a rainfall parameter that is a function of height that can be passed in to some existing code. The use of functions is perfect for this. 

In [7]:
rainfall_exponent = fn.parameter(2.2)
rainfall = scaled_height**rainfall_exponent
print(rainfall)
print(rainfall.evaluate(mesh))

quagmire.fn: (((h(X,Y))*(2.0))+(1.0))**(2.2)
[236.70026345 236.70026345 236.70026345 ... 236.70026345 236.70026345
 236.70026345]


The rainfall definition is live to any changes in the height but we can also adjust the rainfall parameters on the fly ... 

In [8]:
height.data = np.sin(mesh.coords[:,0])
print("Height:", height.data)
print("Rainfall Fn evaluation:",rainfall.evaluate(mesh))
print("Rainfall Direct       :",(height.data*2.0+10.0)**2.2)

# change definition of rainfall coefficient but not functional form

rainfall_exponent.value = 1.0
print("Rainfall Fn evaluation:",rainfall.evaluate(mesh))
print("Rainfall Direct       :",(height.data*2.0+10.0)**2.2)

Height: [ 0.02828304 -0.01414116 -0.01413704 ...  0.68496455  0.68700669
  0.68822664]
Rainfall Fn evaluation: [160.46834176 157.50485419 157.50514032 ... 210.21662774 210.38279282
 210.48209232]
Rainfall Direct       : [160.46834176 157.50485419 157.50514032 ... 210.21662774 210.38279282
 210.48209232]
Rainfall Fn evaluation: [10.05656607  9.97171768  9.97172591 ... 11.36992911 11.37401337
 11.37645327]
Rainfall Direct       : [160.46834176 157.50485419 157.50514032 ... 210.21662774 210.38279282
 210.48209232]


While functions are most useful because they are not computed once and for all, it is also possible to compute their values and assign to a variable. Just be aware that, at this point, numpy has  a greater richness of operators than `quagmire.function`. We can rewrite the above assignment to the height variable using the `coord` function that extracts values of the x or y ( 0 or 1 ) coordinate direction from the locations given as arguments to `evaluate`.

In [9]:
height.data = fn.math.sin(fn.misc.coord(0)).evaluate(mesh)
print("Height:  ", height.data)
print("Height = ", fn.math.sin(fn.misc.coord(0)).description)

Height:   [ 0.02828304 -0.01414116 -0.01413704 ...  0.68496455  0.68700669
  0.68822664]
Height =  SIN(X)


### Operator overloading for +, - , *, **, /

We define addition / subtraction (negation), multiplication, division, and raising to arbitrary power for mesh variables and parameters and the meaning is carried over from `numpy` - i.e. generally these are element-by-element operations on the underlying data vector and require the data structures to have compatible sizes.

It is common to compute a power law of the magnitude of the local slope. 

$$
 k = \left| \nabla h \right|^a
$$

In [15]:
dhdx, dhdy = fn.math.grad(height)
slope = (dhdx**2 + dhdy**2)**0.5
a = fn.parameter(1.3)
k = slope**a

print(k)
print(k.evaluate(mesh))


quagmire.fn: ((((d(h(X,Y))/dX)**(2.0))+((d(h(X,Y))/dY)**(2.0)))**(0.5))**(1.3)
[0.99944353 0.9998964  0.9998964  ... 0.66916704 0.6668987  0.6655553 ]


### Gradients

Variables associated with a mesh also have the capacity to form spatial derivatives anywhere. This is provided by the `stripy` gradient routines in the case of triangulations. The gradient can be formed from any lazy function by evaluating it at the mesh points and then obtaining values of derivatives anywhere via stripy. In the case of the spatially invariant `parameter` objects, the derivatives are identically zero.

_Note: there is no symbolic differentiation in the functions module._

In [11]:
dhdx = height.fn_gradient(0)
print(dhdx.description)
dh1dy = scaled_height.fn_gradient(1)
print(dh1dy.description)

d(h(X,Y))/dX
d(((h(X,Y))*(2.0))+(1.0))/dY


Gradients are also accessible through the `grad`, `div` and `curl` operators as follows

In [12]:
gradx, grady = fn.math.grad(height)
div_grad_h = fn.math.div(gradx, grady)
curl_grad_h = fn.math.curl(gradx, grady)
print("Div.Grad(h)  = ", div_grad_h.description)
print("Curl.Grad(h) = ", curl_grad_h.description)

Div.Grad(h)  =  d(d(h(X,Y))/dX)/dX + d(d(h(X,Y))/dY)/dY
Curl.Grad(h) =  d(d(h(X,Y))/dY)/dX - d(d(h(X,Y))/dX)/dY


The following should all evaluate to zero everywhere and so act as a test on the accuracy of the gradient operator 

In [13]:
print("dhdX (error) = ", (gradx-fn.math.cos(fn.misc.coord(0))).evaluate(mesh))
print("dhdY (error) = ",  grady.evaluate(mesh))
print("Curl.Grad(h) (error) = ", curl_grad_h.evaluate(mesh))

dhdX (error) =  [-2.80354866e-05  2.02998153e-05  2.02415983e-05 ...  5.59219575e-03
  5.60239803e-03  5.62280080e-03]
dhdY (error) =  [ 7.6458605e-08 -1.8433055e-05  1.8415878e-05 ... -1.3181510e-04
 -9.0372239e-05 -5.1293173e-05]
Curl.Grad(h) (error) =  [ 2.7576748e-06 -1.7702088e-03  1.7818911e-03 ...  4.0621040e-03
  2.5112508e-03  1.5058587e-03]
